version: '3'
services:
  db:
      image: mongo
      container_name: planner-mongo
      restart: always
      ports:
        - 5522:27017
      volumes:
        - ./db:/data/db
        - /etc/localtime:/etc/localtime:ro

  server:                                 
    container_name: planner-server     
    restart: always                     # 重启策略: 容器退出时总是重启容器
    build:
      context: ./                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./docker/server.Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - DB_URL=mongodb://db:27017
      - DB_NAME=planner
      - JWT_SECRET=fasdf234
    volumes:                           
      - ./public:/app/public                 
    ports:                              # 映射端口
      - 8000:80
    depends_on:                          # 依赖于server容器，被依赖容器启动后此web容器才可启动
      - db

  client:                                 
    container_name: planner-client     
    restart: always                     # 重启策略: 容器退出时总是重启容器
    build:
      context: ./                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./docker/client.Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - API_URL=http://6.6.6.6/
    volumes:                            # 在线文件
      - ./public:/usr/share/nginx/html/public  
      - ./nginx-log:/var/log/nginx               
    ports:
      - 7000:80                        # 映射端口
    depends_on:                         # 依赖于server容器，被依赖容器启动后此web容器才可启动
      - server