name: CI

on:
  push:
    tags:
      - '**'
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2     
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Dump env
      run: export VERSION=$(echo "${{github.ref}}"" | grep -P "([0-9]+.[0-9]+.[0-9]+)" -o)

    - name: Echo help
      run: docker buildx build --help
    - name: Build
      run: docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t banknight/planner-server:$VERSION -f ./docker/server.Dockerfile . 
            
