name: CI

on:
  push:
    tags:
      - '**'
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tags
      uses: actions/checkout@v2 
      with:  
        ref: ${{github.ref}}   
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Dump env
      run: export VERSION=$(echo "${{github.ref}}"" | grep -P "([0-9]+.[0-9]+.[0-9]+)" -o)
    - name: Docker login
      run: 
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }}  --password-stdin \
    - name: Build
      run: docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/planner-server:$VERSION -f ./docker/server.Dockerfile . 

  client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tags
      uses: actions/checkout@v2 
      with:  
        ref: ${{github.ref}}  
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Dump env
      run: export VERSION=$(echo "${{github.ref}}"" | grep -P "([0-9]+.[0-9]+.[0-9]+)" -o)
    - name: Docker login
      run: 
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }}  --password-stdin \
    - name: Build
      run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/planner-client:$VERSION -f ./docker/client.Dockerfile .             
